import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { ContinentePage } from '../continente/continente';

@IonicPage()
@Component({
  selector: 'page-pais',
  templateUrl: 'pais.html',
})
export class PaisPage {
  items;
  constructor(public navCtrl: NavController, public navParams: NavParams) {
    this.initializeItems();
  }

  initializeItems() {
    this.items = [
      {'pais':'Afeganistão', 'capital' :'Cabul', 'continente' : 'Ásia'},
      {'pais':'África do Sul', 'capital' :'Pretória', 'continente' : ' África'},
      {'pais':'Albânia', 'capital' :'Tirana', 'continente' : ' Europa'},
      {'pais':'Alemanha', 'capital' :'Berlim', 'continente' : ' Europa'},
      {'pais':'Andorra', 'capital' :'Andorra-a-Velha', 'continente' : ' Europa'},
      {'pais':'Angola', 'capital' :'Luanda', 'continente' : ' África'},
      {'pais':'Antiga e Barbuda', 'capital' :'São João', 'continente' : ' América'},
      {'pais':'Arábia Saudita', 'capital' :'Riade', 'continente' : ' Ásia'},
      {'pais':'Argélia', 'capital' :'Argel', 'continente' : ' África'},
      {'pais':'Argentina', 'capital' :'Buenos Aires', 'continente' : 'América'},
      {'pais':'Arménia', 'capital' :'Erevã', 'continente' : ' Ásia'},
      {'pais':'Austrália', 'capital' :'Camberra', 'continente' : ' Oceania'},
      {'pais':'Áustria', 'capital' :'Viena', 'continente' : ' Europa'},
      {'pais':'Azerbaijão', 'capital' :'Bacu', 'continente' : ' Ásia'},
      {'pais':'Bahamas', 'capital' :'Nassau', 'continente' : ' América'},
      {'pais':'Bangladexe', 'capital' :'Daca', 'continente' : ' Ásia'},
      {'pais':'Barbados', 'capital' :'Bridgetown', 'continente' : ' América'},
      {'pais':'Barém', 'capital' :'Manama', 'continente' : ' Ásia'},
      {'pais':'Bélgica', 'capital' :'Bruxelas', 'continente' : ' Europa'},
      {'pais':'Belize', 'capital' :'Belmopã', 'continente' : ' América'},
      {'pais':'Benim', 'capital' :'Porto Novo', 'continente' : ' África'},
      {'pais':'Bielorrússia', 'capital' :'Minsque', 'continente' : ' Europa'},
      {'pais':'Bolívia', 'capital' :'Sucre', 'continente' : ' América'},
      {'pais':'Bósnia e Herzegovina', 'capital' :'Saraievo', 'continente' : ' Europa'},
      {'pais':'Botsuana', 'capital' :'Gaborone', 'continente' : ' África'},
      {'pais':'Brasil', 'capital' :'Brasília', 'continente' : ' América'},
      {'pais':'Brunei', 'capital' :'Bandar Seri Begauã', 'continente' : ' Ásia'},
      {'pais':'Bulgária', 'capital' :'Sófia', 'continente' : ' Europa'},
      {'pais':'Burquina Faso', 'capital' :'Uagadugu', 'continente' : ' África'},
      {'pais':'Burúndi', 'capital' :'Bujumbura', 'continente' : ' África'},
      {'pais':'Butão', 'capital' :'Timbu', 'continente' : ' Ásia'},
      {'pais':'Cabo Verde', 'capital' :'Praia', 'continente' : ' África'},
      {'pais':'Camarões', 'capital' :'Iaundé', 'continente' : ' África'},
      {'pais':'Camboja', 'capital' :'Pnom Pene', 'continente' : ' Ásia'},
      {'pais':'Canadá', 'capital' :'Otava', 'continente' : ' América'},
      {'pais':'Catar', 'capital' :'Doa', 'continente' : ' Ásia'},
      {'pais':'Cazaquistão', 'capital' :'Astana', 'continente' : ' Ásia'},
      {'pais':'Chade', 'capital' :'Jamena', 'continente' : ' África'},
      {'pais':'Chile', 'capital' :'Santiago', 'continente' : ' América'},
      {'pais':'China', 'capital' :'Pequim', 'continente' : ' Ásia'},
      {'pais':'Chipre', 'capital' :'Nicósia', 'continente' : ' Europa'},
      {'pais':'Colômbia', 'capital' :'Bogotá', 'continente' : ' América'},
      {'pais':'Comores', 'capital' :'Moroni', 'continente' : ' África'},
      {'pais':'Congo-Brazzaville', 'capital' :'Brazavile', 'continente' : ' África'},
      {'pais':'Coreia do Norte', 'capital' :'Pionguiangue', 'continente' : ' Ásia'},
      {'pais':'Coreia do Sul', 'capital' :'Seul', 'continente' : ' Ásia'},
      {'pais':'Cosovo', 'capital' :'Pristina', 'continente' : ' Europa'},
      {'pais':'Costa do Marfim', 'capital' :'Iamussucro', 'continente' : ' África'},
      {'pais':'Costa Rica', 'capital' :'São José', 'continente' : ' América'},
      {'pais':'Croácia', 'capital' :'Zagrebe', 'continente' : ' Europa'},
      {'pais':'Cuaite', 'capital' :'Cidade do Cuaite', 'continente' : ' Ásia'},
      {'pais':'Cuba', 'capital' :'Havana', 'continente' : ' América'},
      {'pais':'Dinamarca', 'capital' :'Copenhaga', 'continente' : ' Europa'},
      {'pais':'Dominica', 'capital' :'Roseau', 'continente' : ' América'},
      {'pais':'Egito', 'capital' :'Cairo', 'continente' : ' África'},
      {'pais':'Emirados Árabes Unidos', 'capital' :'Abu Dabi', 'continente' : ' Ásia'},
      {'pais':'Equador', 'capital' :'Quito', 'continente' : ' América'},
      {'pais':'Eritreia', 'capital' :'Asmara', 'continente' : ' África'},
      {'pais':'Eslováquia', 'capital' :'Bratislava', 'continente' : ' Europa'},
      {'pais':'Eslovénia', 'capital' :'Liubliana', 'continente' : ' Europa'},
      {'pais':'Espanha', 'capital' :'Madrid', 'continente' : ' Europa'},
      {'pais':'Estado da Palestina', 'capital' :'Jerusalém Oriental', 'continente' : ' Ásia'},
      {'pais':'Estados Unidos', 'capital' :'Washington, D.C.', 'continente' : ' América'},
      {'pais':'Estónia', 'capital' :'Talim', 'continente' : ' Europa'},
      {'pais':'Etiópia', 'capital' :'Adis Abeba', 'continente' : ' África'},
      {'pais':'Fiji', 'capital' :'Suva', 'continente' : ' Oceania'},
      {'pais':'Filipinas', 'capital' :'Manila', 'continente' : ' Ásia'},
      {'pais':'Finlândia', 'capital' :'Helsínquia', 'continente' : ' Europa'},
      {'pais':'França', 'capital' :'Paris', 'continente' : ' Europa'},
      {'pais':'Gabão', 'capital' :'Libreville', 'continente' : ' África'},
      {'pais':'Gâmbia', 'capital' :'Banjul', 'continente' : ' África'},
      {'pais':'Gana', 'capital' :'Acra', 'continente' : ' África'},
      {'pais':'Geórgia', 'capital' :'Tebilíssi', 'continente' : ' Ásia'},
      {'pais':'Granada', 'capital' :'São Jorge', 'continente' : ' América'},
      {'pais':'Grécia', 'capital' :'Atenas', 'continente' : ' Europa'},
      {'pais':'Guatemala', 'capital' :'Cidade da Guatemala', 'continente' : ' América'},
      {'pais':'Guiana', 'capital' :'Georgetown', 'continente' : ' América'},
      {'pais':'Guiné', 'capital' :'Conacri', 'continente' : ' África'},
      {'pais':'Guiné Equatorial', 'capital' :'Malabo', 'continente' : ' África'},
      {'pais':'Guiné-Bissau', 'capital' :'Bissau', 'continente' : ' África'},
      {'pais':'Haiti', 'capital' :'Porto Príncipe', 'continente' : ' América'},
      {'pais':'Honduras', 'capital' :'Tegucigalpa', 'continente' : ' América'},
      {'pais':'Hungria', 'capital' :'Budapeste', 'continente' : ' Europa'},
      {'pais':'Iémen', 'capital' :'Saná', 'continente' : ' Ásia'},
      {'pais':'Ilhas Marechal', 'capital' :'Majuro', 'continente' : ' Oceania'},
      {'pais':'Índia', 'capital' :'Nova Déli', 'continente' : ' Ásia'},
      {'pais':'Indonésia', 'capital' :'Jacarta', 'continente' : ' Ásia'},
      {'pais':'Irão', 'capital' :'Teerão', 'continente' : ' Ásia'},
      {'pais':'Iraque', 'capital' :'Bagdade', 'continente' : ' Ásia'},
      {'pais':'Irlanda', 'capital' :'Dublim', 'continente' : ' Europa'},
      {'pais':'Islândia', 'capital' :'Reiquiavique', 'continente' : ' Europa'},
      {'pais':'Israel', 'capital' :'Jerusalém', 'continente' : ' Ásia'},
      {'pais':'Itália', 'capital' :'Roma', 'continente' : ' Europa'},
      {'pais':'Jamaica', 'capital' :'Kingston', 'continente' : ' América'},
      {'pais':'Japão', 'capital' :'Tóquio', 'continente' : ' Ásia'},
      {'pais':'Jibuti', 'capital' :'Jibuti', 'continente' : ' África'},
      {'pais':'Jordânia', 'capital' :'Amã', 'continente' : ' Ásia'},
      {'pais':'Laus', 'capital' :'Vienciana', 'continente' : ' Ásia'},
      {'pais':'Lesoto', 'capital' :'Maseru', 'continente' : ' África'},
      {'pais':'Letónia', 'capital' :'Riga', 'continente' : ' Europa'},
      {'pais':'Líbano', 'capital' :'Beirute', 'continente' : ' Ásia'},
      {'pais':'Libéria', 'capital' :'Monróvia', 'continente' : ' África'},
      {'pais':'Líbia', 'capital' :'Trípoli', 'continente' : ' África'},
      {'pais':'Listenstaine', 'capital' :'Vaduz', 'continente' : ' Europa'},
      {'pais':'Lituânia', 'capital' :'Vílnius', 'continente' : ' Europa'},
      {'pais':'Luxemburgo', 'capital' :'Luxemburgo', 'continente' : ' Europa'},
      {'pais':'Macedónia', 'capital' :'Escópia', 'continente' : ' Europa'},
      {'pais':'Madagáscar', 'capital' :'Antananarivo', 'continente' : ' África'},
      {'pais':'Malásia', 'capital' :'Cuala Lumpur', 'continente' : ' Ásia'},
      {'pais':'Maláui', 'capital' :'Lilôngue', 'continente' : ' África'},
      {'pais':'Maldivas', 'capital' :'Malé', 'continente' : ' Ásia'},
      {'pais':'Mali', 'capital' :'Bamaco', 'continente' : ' África'},
      {'pais':'Malta', 'capital' :'Valeta', 'continente' : ' Europa'},
      {'pais':'Marrocos', 'capital' :'Rebate', 'continente' : ' África'},
      {'pais':'Maurícia', 'capital' :'Porto Luís', 'continente' : ' África'},
      {'pais':'Mauritânia', 'capital' :'Nuaquechote', 'continente' : ' África'},
      {'pais':'México', 'capital' :'Cidade do México', 'continente' : ' América'},
      {'pais':'Mianmar', 'capital' :'Nepiedó', 'continente' : ' Ásia'},
      {'pais':'Micronésia', 'capital' :'Paliquir', 'continente' : ' Oceania'},
      {'pais':'Moçambique', 'capital' :'Maputo', 'continente' : ' África'},
      {'pais':'Moldávia', 'capital' :'Quixinau', 'continente' : ' Europa'},
      {'pais':'Mónaco', 'capital' :'Mónaco', 'continente' : ' Europa'},
      {'pais':'Mongólia', 'capital' :'Ulã Bator', 'continente' : ' Ásia'},
      {'pais':'Montenegro', 'capital' :'Podgoritsa', 'continente' : ' Europa'},
      {'pais':'Namíbia', 'capital' :'Vinduque', 'continente' : ' África'},
      {'pais':'Nauru', 'capital' :'Iarém', 'continente' : ' Oceania'},
      {'pais':'Nepal', 'capital' :'Catmandu', 'continente' : ' Ásia'},
      {'pais':'Nicarágua', 'capital' :'Manágua', 'continente' : ' América'},
      {'pais':'Níger', 'capital' :'Niamei', 'continente' : ' África'},
      {'pais':'Nigéria', 'capital' :'Abuja', 'continente' : ' África'},
      {'pais':'Noruega', 'capital' :'Oslo', 'continente' : ' Europa'},
      {'pais':'Nova Zelândia', 'capital' :'Wellington', 'continente' : ' Oceania'},
      {'pais':'Omã', 'capital' :'Mascate', 'continente' : ' Ásia'},
      {'pais':'Países Baixos', 'capital' :'Amesterdão', 'continente' : ' Europa'},
      {'pais':'Palau', 'capital' :'Ngerulmud', 'continente' : ' Oceania'},
      {'pais':'Panamá', 'capital' :'Cidade do Panamá', 'continente' : ' América'},
      {'pais':'Papua Nova Guiné', 'capital' :'Porto Moresby', 'continente' : ' Oceania'},
      {'pais':'Paquistão', 'capital' :'Islamabade', 'continente' : ' Ásia'},
      {'pais':'Paraguai', 'capital' :'Assunção', 'continente' : ' América'},
      {'pais':'Peru', 'capital' :'Lima', 'continente' : ' América'},
      {'pais':'Polónia', 'capital' :'Varsóvia', 'continente' : ' Europa'},
      {'pais':'Portugal', 'capital' :'Lisboa', 'continente' : ' Europa'},
      {'pais':'Quénia', 'capital' :'Nairóbi', 'continente' : ' África'},
      {'pais':'Quirguistão', 'capital' :'Bisqueque', 'continente' : ' Ásia'},
      {'pais':'Quiribáti', 'capital' :'Taraua do Sul', 'continente' : ' Oceania'},
      {'pais':'Reino Unido', 'capital' :'Londres', 'continente' : ' Europa'},
      {'pais':'República Centro-Africana', 'capital' :'Bangui', 'continente' : ' África'},
      {'pais':'República Checa', 'capital' :'Praga', 'continente' : ' Europa'},
      {'pais':'República Democrática do Congo', 'capital' :'Quinxassa', 'continente' : ' África'},
      {'pais':'República Dominicana', 'capital' :'São Domingos', 'continente' : ' América'},
      {'pais':'Roménia', 'capital' :'Bucareste', 'continente' : ' Europa'},
      {'pais':'Ruanda', 'capital' :'Quigali', 'continente' : ' África'},
      {'pais':'Rússia', 'capital' :'Moscovo', 'continente' : ' Europa'},
      {'pais':'Salomão', 'capital' :'Honiara', 'continente' : ' Oceania'},
      {'pais':'Salvador', 'capital' :'São Salvador', 'continente' : ' América'},
      {'pais':'Samoa', 'capital' :'Apia', 'continente' : ' Oceania'},
      {'pais':'Santa Lúcia', 'capital' :'Castries', 'continente' : ' América'},
      {'pais':'São Cristóvão e Neves', 'capital' :'Basseterre', 'continente' : ' América'},
      {'pais':'São Marinho', 'capital' :'São Marinho', 'continente' : ' Europa'},
      {'pais':'São Tomé e Príncipe', 'capital' :'São Tomé', 'continente' : ' África'},
      {'pais':'São Vicente e Granadinas', 'capital' :'Kingstown', 'continente' : ' América'},
      {'pais':'Seicheles', 'capital' :'Vitória', 'continente' : ' África'},
      {'pais':'Senegal', 'capital' :'Dacar', 'continente' : ' África'},
      {'pais':'Serra Leoa', 'capital' :'Freetown', 'continente' : ' África'},
      {'pais':'Sérvia', 'capital' :'Belgrado', 'continente' : ' Europa'},
      {'pais':'Singapura', 'capital' :'Singapura', 'continente' : ' Ásia'},
      {'pais':'Síria', 'capital' :'Damasco', 'continente' : ' Ásia'},
      {'pais':'Somália', 'capital' :'Mogadíscio', 'continente' : ' África'},
      {'pais':'Sri Lanca', 'capital' :'Sri Jaiavardenapura-Cota', 'continente' : ' Ásia'},
      {'pais':'Suazilândia', 'capital' :'Lobamba', 'continente' : ' África'},
      {'pais':'Sudão', 'capital' :'Cartum', 'continente' : ' África'},
      {'pais':'Sudão do Sul', 'capital' :'Juba', 'continente' : ' África'},
      {'pais':'Suécia', 'capital' :'Estocolmo', 'continente' : ' Europa'},
      {'pais':'Suíça', 'capital' :'Berna', 'continente' : ' Europa'},
      {'pais':'Suriname', 'capital' :'Paramaribo', 'continente' : ' América'},
      {'pais':'Tailândia', 'capital' :'Banguecoque', 'continente' : ' Ásia'},
      {'pais':'Taiuã', 'capital' :'Taipé', 'continente' : ' Ásia'},
      {'pais':'Tajiquistão', 'capital' :'Duchambé', 'continente' : ' Ásia'},
      {'pais':'Tanzânia', 'capital' :'Dodoma', 'continente' : ' África'},
      {'pais':'Timor-Leste', 'capital' :'Díli', 'continente' : ' Oceania'},
      {'pais':'Togo', 'capital' :'Lomé', 'continente' : ' África'},
      {'pais':'Tonga', 'capital' :'Nucualofa', 'continente' : ' Oceania'},
      {'pais':'Trindade e Tobago', 'capital' :'Porto de Espanha', 'continente' : ' América'},
      {'pais':'Tunísia', 'capital' :'Tunes', 'continente' : ' África'},
      {'pais':'Turcomenistão', 'capital' :'Asgabate', 'continente' : ' Ásia'},
      {'pais':'Turquia', 'capital' :'Ancara', 'continente' : ' Ásia'},
      {'pais':'Tuvalu', 'capital' :'Funafuti', 'continente' : ' Oceania'},
      {'pais':'Ucrânia', 'capital' :'Quieve', 'continente' : ' Europa'},
      {'pais':'Uganda', 'capital' :'Campala', 'continente' : ' África'},
      {'pais':'Uruguai', 'capital' :'Montevideu', 'continente' : ' América'},
      {'pais':'Usbequistão', 'capital' :'Tasquente', 'continente' : ' Ásia'},
      {'pais':'Vanuatu', 'capital' :'Porto Vila', 'continente' : ' Oceania'},
      {'pais':'Vaticano', 'capital' :'Vaticano', 'continente' : ' Europa'},
      {'pais':'Venezuela', 'capital' :'Caracas', 'continente' : ' América'},
      {'pais':'Vietname', 'capital' :'Hanói', 'continente' : ' Ásia'},
      {'pais':'Zâmbia', 'capital' :'Lusaca', 'continente' : ' África'},
      {'pais':'Zimbábue', 'capital' :'Harare', 'continente' : ' África'}
    ];
  }

  getItems(ev) {
    this.initializeItems();
    var val = ev.target.value;
    if (val && val.trim() != '') {
      this.items = this.items.filter((item) => {
        return (item.pais.toLowerCase().indexOf(val.toLowerCase()) > -1);
      })
    }
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad PaisPage');
  }

}
